In [7]:
import pandas as pd

In [8]:
# Load the dataset
data1 = pd.read_csv('youtube_dataset.csv', encoding='latin-1')

In [10]:
# Sort the DataFrame by 'Subscribers' column in descending order
data= data1.sort_values(by='subscribers', ascending=False)

In [11]:
# Function to calculate the distribution of channeltype from the top 1000 records
def calculate_channel_distribution(data):
    channel_distribution = data['channeltype'].value_counts(normalize=True)
    return channel_distribution

In [12]:
def load_data_top_1000(data):
    top_1000_data = data.head(1000)
    top_1000_data.to_csv('top_1000_channels.csv', index=False)
    return top_1000_data

In [13]:
# Calculate channel distribution
channel_distribution_result = calculate_channel_distribution(data)

In [14]:
print(channel_distribution_result)

Entertainment    0.281717
Music            0.206466
Games            0.121978
People           0.106493
Comedy           0.074708
Howto            0.060581
Film             0.047813
Education        0.038576
Tech             0.021190
Sports           0.015213
News             0.014942
Autos            0.003803
Travel           0.002988
Animals          0.002445
Nonprofit        0.000815
Shows            0.000272
Name: channeltype, dtype: float64

In [15]:
# Call the load_data_top_1000 function
top_1000_data = load_data_top_1000(data)

In [16]:
# Display the loaded DataFrame
top_1000_data.head()

,web-scraper-order,web-scraper-start-url,userID,userID-href,name,uploads,subscribers,videoviews,country,channeltype,usercreated,grade,YouTube_Link,YouTube_Link-href,TwitterHandle,TwitterHandle-href,InstagramHandle,InstagramHandle-href,MonthlyEarnings,YearlyEarnings
0,1553043067-5148,https://socialblade.com/youtube/top/5000/mosts...,PewDiePie,https://socialblade.com/youtube/c/pewdiepie,PewDiePie,3779,90210848,20772365682,US,Entertainment,"Apr 29th, 2010",A,NaN,https://youtube.com/channel/UC-lHJZR3Gqxm24_Vd...,NaN,https://twitter.com/pewdiepie,NaN,https://instagram.com/pewdiepie,66.9K - 1.1M,802.3K - 12.8M
1,1553043063-5147,https://socialblade.com/youtube/top/5000/mosts...,T-Series,https://socialblade.com/youtube/c/tseriesmusic,T-Series,13218,90194329,65092058996,IN,Music,"Mar 13th, 2006",A++,NaN,https://youtube.com/channel/UCq-Fj5jknLsUf-MWS...,NaN,https://instagram.com/tseries.official,NaN,https://plus.google.com/115156822320080163368,635.6K - 10.2M,7.6M - 122M
2,1553043059-5146,https://socialblade.com/youtube/top/5000/mosts...,Gaming,https://socialblade.com/youtube/channel/UCOpNc...,Gaming,0,81888222,0,NaN,Games,"Dec 15th, 2013",D-,NaN,https://youtube.com/channel/UCOpNcN46UbXVtpKMr...,NaN,NaN,NaN,https://youtube.com/channel/UCOpNcN46UbXVtpKMr...,0 - 0,0 - 0
3,1553043055-5145,https://socialblade.com/youtube/top/5000/mosts...,YouTube Movies,https://socialblade.com/youtube/channel/UClgRk...,YouTube Movies,0,77413743,0,NaN,Film,"Jun 10th, 2015",D-,NaN,https://youtube.com/channel/UClgRkhTL3_hImCAmd...,NaN,NaN,NaN,https://youtube.com/channel/UClgRkhTL3_hImCAmd...,0 - 0,0 - 0
4,1553043051-5144,https://socialblade.com/youtube/top/5000/mosts...,Sports,https://socialblade.com/youtube/channel/UCEgdi...,Sports,0,75622870,0,NaN,Sports,"Dec 15th, 2013",D-,NaN,https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...,NaN,NaN,NaN,https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...,0 - 0,0 - 0

In [17]:
# Display the loaded DataFrame
top_1000_data.head()

,web-scraper-order,web-scraper-start-url,userID,userID-href,name,uploads,subscribers,videoviews,country,channeltype,usercreated,grade,YouTube_Link,YouTube_Link-href,TwitterHandle,TwitterHandle-href,InstagramHandle,InstagramHandle-href,MonthlyEarnings,YearlyEarnings
0,1553043067-5148,https://socialblade.com/youtube/top/5000/mosts...,PewDiePie,https://socialblade.com/youtube/c/pewdiepie,PewDiePie,3779,90210848,20772365682,US,Entertainment,"Apr 29th, 2010",A,NaN,https://youtube.com/channel/UC-lHJZR3Gqxm24_Vd...,NaN,https://twitter.com/pewdiepie,NaN,https://instagram.com/pewdiepie,66.9K - 1.1M,802.3K - 12.8M
1,1553043063-5147,https://socialblade.com/youtube/top/5000/mosts...,T-Series,https://socialblade.com/youtube/c/tseriesmusic,T-Series,13218,90194329,65092058996,IN,Music,"Mar 13th, 2006",A++,NaN,https://youtube.com/channel/UCq-Fj5jknLsUf-MWS...,NaN,https://instagram.com/tseries.official,NaN,https://plus.google.com/115156822320080163368,635.6K - 10.2M,7.6M - 122M
2,1553043059-5146,https://socialblade.com/youtube/top/5000/mosts...,Gaming,https://socialblade.com/youtube/channel/UCOpNc...,Gaming,0,81888222,0,NaN,Games,"Dec 15th, 2013",D-,NaN,https://youtube.com/channel/UCOpNcN46UbXVtpKMr...,NaN,NaN,NaN,https://youtube.com/channel/UCOpNcN46UbXVtpKMr...,0 - 0,0 - 0
3,1553043055-5145,https://socialblade.com/youtube/top/5000/mosts...,YouTube Movies,https://socialblade.com/youtube/channel/UClgRk...,YouTube Movies,0,77413743,0,NaN,Film,"Jun 10th, 2015",D-,NaN,https://youtube.com/channel/UClgRkhTL3_hImCAmd...,NaN,NaN,NaN,https://youtube.com/channel/UClgRkhTL3_hImCAmd...,0 - 0,0 - 0
4,1553043051-5144,https://socialblade.com/youtube/top/5000/mosts...,Sports,https://socialblade.com/youtube/channel/UCEgdi...,Sports,0,75622870,0,NaN,Sports,"Dec 15th, 2013",D-,NaN,https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...,NaN,NaN,NaN,https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...,0 - 0,0 - 0

In [20]:
data2 = pd.read_csv('top_1000_channels.csv')
data2.head()

,web-scraper-order,web-scraper-start-url,userID,userID-href,name,uploads,subscribers,videoviews,country,channeltype,usercreated,grade,YouTube_Link,YouTube_Link-href,TwitterHandle,TwitterHandle-href,InstagramHandle,InstagramHandle-href,MonthlyEarnings,YearlyEarnings
0,1553043067-5148,https://socialblade.com/youtube/top/5000/mosts...,PewDiePie,https://socialblade.com/youtube/c/pewdiepie,PewDiePie,3779,90210848,20772365682,US,Entertainment,"Apr 29th, 2010",A,NaN,https://youtube.com/channel/UC-lHJZR3Gqxm24_Vd...,NaN,https://twitter.com/pewdiepie,NaN,https://instagram.com/pewdiepie,66.9K - 1.1M,802.3K - 12.8M
1,1553043063-5147,https://socialblade.com/youtube/top/5000/mosts...,T-Series,https://socialblade.com/youtube/c/tseriesmusic,T-Series,13218,90194329,65092058996,IN,Music,"Mar 13th, 2006",A++,NaN,https://youtube.com/channel/UCq-Fj5jknLsUf-MWS...,NaN,https://instagram.com/tseries.official,NaN,https://plus.google.com/115156822320080163368,635.6K - 10.2M,7.6M - 122M
2,1553043059-5146,https://socialblade.com/youtube/top/5000/mosts...,Gaming,https://socialblade.com/youtube/channel/UCOpNc...,Gaming,0,81888222,0,NaN,Games,"Dec 15th, 2013",D-,NaN,https://youtube.com/channel/UCOpNcN46UbXVtpKMr...,NaN,NaN,NaN,https://youtube.com/channel/UCOpNcN46UbXVtpKMr...,0 - 0,0 - 0
3,1553043055-5145,https://socialblade.com/youtube/top/5000/mosts...,YouTube Movies,https://socialblade.com/youtube/channel/UClgRk...,YouTube Movies,0,77413743,0,NaN,Film,"Jun 10th, 2015",D-,NaN,https://youtube.com/channel/UClgRkhTL3_hImCAmd...,NaN,NaN,NaN,https://youtube.com/channel/UClgRkhTL3_hImCAmd...,0 - 0,0 - 0
4,1553043051-5144,https://socialblade.com/youtube/top/5000/mosts...,Sports,https://socialblade.com/youtube/channel/UCEgdi...,Sports,0,75622870,0,NaN,Sports,"Dec 15th, 2013",D-,NaN,https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...,NaN,NaN,NaN,https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...,0 - 0,0 - 0

In [7]:

pip install pymysql

Requirement already satisfied: pymysql in c:\users\rehal\anaconda3\lib\site-packages (1.0.2)
Note: you may need to restart the kernel to use updated packages.

In [8]:
# How to create an engine and connect to a database

# import required libraries
import pandas as pd
from sqlalchemy import create_engine
import pymysql

In [13]:
# create engine
engine = create_engine('mysql+pymysql://usert:password@localhost/assignment4')

In [14]:
# connection string
conn = engine.connect()

In [15]:
# read a simple query into DataFrame
df = pd.read_sql("SELECT * FROM assignment4.youtube_dataset", conn)

In [16]:
# print DataFrame
print(df.head())

  web-scraper-order                              web-scraper-start-url  \
0   1553043067-5148  https://socialblade.com/youtube/top/5000/mosts...
1   1553043063-5147  https://socialblade.com/youtube/top/5000/mosts...
2   1553043059-5146  https://socialblade.com/youtube/top/5000/mosts...
3   1553043055-5145  https://socialblade.com/youtube/top/5000/mosts...
4   1553043051-5144  https://socialblade.com/youtube/top/5000/mosts...

           userID                                        userID-href  \
0       PewDiePie        https://socialblade.com/youtube/c/pewdiepie
1        T-Series     https://socialblade.com/youtube/c/tseriesmusic
2          Gaming  https://socialblade.com/youtube/channel/UCOpNc...
3  YouTube Movies  https://socialblade.com/youtube/channel/UClgRk...
4          Sports  https://socialblade.com/youtube/channel/UCEgdi...

             name  uploads  subscribers   videoviews country    channeltype  \
0       PewDiePie     3779     90210848  20772365682      US  Entertainment
1        T-Series    13218     90194329  65092058996      IN          Music
2          Gaming        0     81888222            0                  Games
3  YouTube Movies        0     77413743            0                   Film
4          Sports        0     75622870            0                 Sports

      usercreated grade YouTube_Link  \
0  Apr 29th, 2010     A
1  Mar 13th, 2006   A++
2  Dec 15th, 2013    D-
3  Jun 10th, 2015    D-
4  Dec 15th, 2013    D-

                                   YouTube_Link-href TwitterHandle  \
0  https://youtube.com/channel/UC-lHJZR3Gqxm24_Vd...
1  https://youtube.com/channel/UCq-Fj5jknLsUf-MWS...
2  https://youtube.com/channel/UCOpNcN46UbXVtpKMr...          None
3  https://youtube.com/channel/UClgRkhTL3_hImCAmd...          None
4  https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...          None

                       TwitterHandle-href InstagramHandle  \
0           https://twitter.com/pewdiepie
1  https://instagram.com/tseries.official
2
3
4

                                InstagramHandle-href   MonthlyEarnings  \
0                    https://instagram.com/pewdiepie    €66.9K - €1.1M
1      https://plus.google.com/115156822320080163368  €635.6K - €10.2M
2  https://youtube.com/channel/UCOpNcN46UbXVtpKMr...           €0 - €0
3  https://youtube.com/channel/UClgRkhTL3_hImCAmd...           €0 - €0
4  https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...           €0 - €0

     YearlyEarnings
0  €802.3K - €12.8M
1     €7.6M - €122M
2           €0 - €0
3           €0 - €0
4           €0 - €0

In [18]:
# Specify the table name in the database
table_name = 'top_1000_channels.csv'

In [21]:
# Write the DataFrame to the MySQL table
data2.to_sql(table_name, con=engine, if_exists='replace', index=False)

1000